### ISSUE TITLE
Podman-compose down always stalls at rm philomenaderpi

### ISSUE THREAD

**Issue by parasprite** [philomena-dev/philomena#69]
I just interrupt and then run the command again and it works fine but it's a little annoying.

Probably won't help but here's the traceback after interrupting:
```podman pod rm philomenaderpi
^CTraceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.6.dev0', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1267, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 755, in run
    cmd(self, args)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 939, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1088, in compose_down
    compose.podman.run(["pod", "rm", pod["name"]], sleep=0)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 641, in run
    print(p.wait())
  File "/usr/lib64/python3.9/subprocess.py", line 1185, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1915, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.9/subprocess.py", line 1873, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt```

**Comment by liamwhite** [comment]
That is a bug in podman-compose, nothing I can do about it.
